package appv2.core;

public enum ECardResponse {
    RC_OK,
    RC_ERR,
    RC_OK_KNOCKED_OUT,
    RC_CHOOSE_ANY_PLAYER,
    RC_CHOOSE_ANY_PLAYER_SELF_EXCLUDED,
    RC_CHOOSE_ANY_PLAYER_SELF_EXCLUDED_WITH_INTEGER,
}
